FROM node:18

RUN mkdir /app
WORKDIR /app

COPY . /app

RUN npm ci
RUN npm install -g --unsafe-perm prisma
RUN npx prisma generate

EXPOSE 3000

RUN apt-get update
RUN apt-get install sqlite3 -y
CMD [ "npm", "run", "start" ]
